root: true
env:
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  project: tsconfig.json
plugins:
  - "@typescript-eslint"
extends:
  - standard
  - plugin:@typescript-eslint/recommended
rules:
  comma-dangle:
    - error
    - always-multiline
  import/order:
    - error
    - newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  max-len:
    - error
    - code: 120
  no-use-before-define:
    - off
  '@typescript-eslint/no-use-before-define':
    - error
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
